name: sig
title: sig
summary: Interactive grep
adopt-info: sig 
description: |
  Interactive grep
  
  Interactive grep (for streaming)

  Usage: sig [OPTIONS]

  Examples:

  $ stern --context kind-kind etcd |& sig
  Or the method to retry command by pressing ctrl+r:
  $ sig --cmd "stern --context kind-kind etcd"

  Archived mode:
  $ cat README.md |& sig -a
  Or
  $ sig -a --cmd "cat README.md"

  Options:
      --retrieval-timeout <RETRIEVAL_TIMEOUT_MILLIS>
            Timeout to read a next line from the stream in milliseconds. [default: 10]
      --render-interval <RENDER_INTERVAL_MILLIS>
            Interval to render a line in milliseconds. [default: 10]
    -q, --queue-capacity <QUEUE_CAPACITY>
            Queue capacity to store lines. [default: 1000]
    -a, --archived
            Archived mode to grep through static data.
    -i, --ignore-case
          Case insensitive search.
        --cmd <CMD>
            Command to execute on initial and retries.
    -h, --help
            Print help (see more with '--help')
    -V, --version
            Print version

license: MIT
base: core24
grade: stable
confinement: strict
compression: lzo

website: https://github.com/ynqa/sig
contact: https://github.com/ynqa/sig
issues: https://github.com/ynqa/sig/issues
source-code: https://github.com/ynqa/sig


apps:
  sig:
    command: bin/sig
    
parts:
  sig:
    source: https://github.com/ynqa/sig
    source-type: git
    plugin: rust
    
    override-pull: |
      craftctl default
      craftctl set version="$(git describe --tags | sed 's/^v//' | cut -d "-" -f1)"
  
